name:                uniter
version:             0.1.0
github:              "githubuser/uniter"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "(c) 2021 Author name here"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/githubuser/uniter#readme>

dependencies:
- base >= 4.12 && < 5
- algebraic-graphs >= 0.6 && < 0.7
- containers >= 0.6 && < 0.7
- deepseq >= 1.4 && < 1.5
- exceptions >= 0.10 && < 0.11
- hashable >= 1.3 && < 1.5
- int-like >= 0.1 && < 0.2
- microlens >= 0.4 && < 0.5
- microlens-mtl >= 0.2 && < 0.3
- mtl >= 2.2 && < 2.3
- pretty-simple >= 4.0 && < 4.1
- recursion-schemes >= 5.2 && < 5.3
- streaming >= 0.2 && < 0.3
- text >= 1.2 && < 2.1
- these >= 1.1 && < 1.2
- transformers >= 0.5 && < 0.7
- unfree >= 0.1 && < 0.2

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- PatternSynonyms
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

executables:
  uniter-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniter

tests:
  uniter-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prop-unit >= 0.1 && < 0.2
    - uniter
