name:                uniter
version:             0.4.0
github:              "ejconlon/uniter"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
category:            Language Tools
synopsis:            A generic variant of Hindley-Milner

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/uniter#readme>

dependencies:
- base >= 4.12 && < 5
- algebraic-graphs >= 0.7 && < 0.8
- bifunctors >= 5.5 && < 5.6
- containers >= 0.6 && < 0.7
- exceptions >= 0.10 && < 0.11
- int-like >= 0.1.2 && < 0.2
- microlens >= 0.4 && < 0.5
- microlens-mtl >= 0.2 && < 0.3
- mtl >= 2.2 && < 2.3
- pretty-simple >= 4.0 && < 4.2
- recursion-schemes >= 5.2 && < 5.3
- text >= 1.2 && < 2.1
- these >= 1.1 && < 1.3
- transformers >= 0.5 && < 0.7

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- PatternSynonyms
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

executables:
  uniter-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniter

tests:
  uniter-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prop-unit >= 0.1 && < 0.2
    - uniter
