resolver: lts-18.26

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- git: git@github.com:ejconlon/int-like.git
  commit: e814624a26d71f02582e5cb9ea0955aa721d509e
- git: git@github.com:ejconlon/prop-unit.git
  commit: 167f919ee66dc2f6f17b9ad952be3921779789ea
- git: git@github.com:ejconlon/unfree.git
  commit: c4eaee614c8a62d8c489dbdc9806db7c735435db
- algebraic-graphs-0.6
